# 1. Create a 3x3x3 array with random values

In [31]:
import numpy as np
randomArr= np.random.randint(1,999,size=(3,3,3))

randomArr

array([[[118, 844, 322],
        [ 72, 636, 259],
        [782,  57, 871]],

       [[ 83,  66, 786],
        [ 41, 140, 529],
        [386, 522, 340]],

       [[534, 540, 581],
        [371, 817, 122],
        [120,  38, 962]]])

# 2.Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [32]:
arr=np.diag([1,2,3,4], -1)
arr

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

# 3.Create a 8x8 matrix and fill it with a checkerboard pattern

In [33]:
arr=np.zeros((8,8))
arr[1::2,::2] = 1
arr[::2,1::2] = 1
print(arr)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


# 4. Normalize a 5x5 random matrix¶


In [49]:
arr1=np.random.random((5,5))
print("Original array is \n",arr1)
from sklearn.preprocessing import normalize
arr2=normalize(arr1)
print("Normalised array is \n",arr2)

Original array is 
 [[0.98046297 0.51123504 0.85737995 0.032192   0.87203419]
 [0.30794128 0.66236108 0.88115393 0.45522998 0.06648017]
 [0.89180324 0.77880354 0.81746112 0.72266868 0.86338408]
 [0.00877028 0.76714483 0.45463999 0.40717767 0.46007055]
 [0.79647374 0.26787047 0.9056808  0.13877373 0.73091953]]
Normalised array is 
 [[0.59457506 0.31002456 0.51993472 0.01952196 0.52882138]
 [0.24963904 0.53695685 0.71432584 0.36904169 0.05389354]
 [0.4881358  0.4262845  0.44744404 0.39555862 0.47258034]
 [0.00809864 0.70839538 0.41982277 0.3759952  0.42483744]
 [0.55227055 0.18573992 0.62799412 0.09622495 0.50681561]]


# 5. How to find common values between two arrays?

In [55]:
arr3=np.array([10,20,30,40,60])
print("First array is \n",arr3)
arr4=np.array([20,40,60,80,100])
print("Second  array is \n",arr4)
comarr=np.intersect1d (arr3, arr4)
print("Common elements are ",comarr)

First array is 
 [10 20 30 40 60]
Second  array is 
 [ 20  40  60  80 100]
Common elements are  [20 40 60]


# 6.How to get the dates of yesterday, today and tomorrow?

In [36]:
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
print("Yestraday: ",yesterday)
today     = np.datetime64('today', 'D')
print("Today: ",today)
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print("Tomorrow: ",tomorrow)

Yestraday:  2021-06-30
Today:  2021-07-01
Tomorrow:  2021-07-02


# 7. Consider two random array A and B, check if they are equal

In [37]:
randomArr1= np.random.randint(1,10,size=(2,2))
print("First array is\n",randomArr1)
randomArr2= np.random.randint(1,10,size=(2,2))
print("Second array is\n",randomArr2)
if ((randomArr1==randomArr2).all()==True):
    print("Equal ")
else:
    print("Not equal ")

First array is
 [[6 7]
 [7 4]]
Second array is
 [[6 2]
 [5 1]]
Not equal 


# 9. How to print all the values of an array?

In [64]:
arr5 = np.arange(51)
np.set_printoptions(threshold=np.inf)
print(arr5)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50]


# 10.Subtract the mean of each row of a matrix¶

In [70]:
print("Original matrix:\n")
arr6= np.random.randint(1,5,size=(3,4))
print(arr6)
print("\nSubtract the mean of each row of the matrix:\n")
arr7 = arr6-arr6.mean(axis=1, keepdims = True)
print(arr7)

Original matrix:

[[2 3 3 3]
 [2 4 1 3]
 [3 3 1 1]]

Subtract the mean of each row of the matrix:

[[-0.75  0.25  0.25  0.25]
 [-0.5   1.5  -1.5   0.5 ]
 [ 1.    1.   -1.   -1.  ]]


# 11.Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)?

In [40]:
a = np.random.randint(1,8,8)
print("Given vector:", a)
b = np.random.randint(a)
c = []
b.sort()
for i in b:
    if i not in c:
        c.append(i)

for j in c:
    a[j] += 1

print("Indexing vector:", b)
print("Result:",a)

Given vector: [2 7 7 5 5 1 3 5]
Indexing vector: [0 0 1 1 1 2 2 2]
Result: [3 8 8 5 5 1 3 5]


# 12.How to get the diagonal of a dot product?

In [76]:
x= [[1,2],[3,4]]
y = [[5,6],[7,8]]
z = np.diag(np.dot(x,y))
z

array([19, 50])

# 13.How to find the most frequent value in an array?

In [82]:
arr8= np.random.randint(0, 100, 30)
print("Original array:")
print(arr8)
print("Most frequent value in the above array:")
print(np.bincount(arr8).argmax())

Original array:
[48 76 92  2  5 28 55 24 42 93 68 20 42 51 17 88 27 42 41 68 99 64 35 75
 36 38 20 54 41 55]
Most frequent value in the above array:
42


# 14.How to get the n largest values of an array?

In [43]:
x = np.arange(99)
print("Original array:")
print(x)
np.random.shuffle(x)
n = 1
print (x[np.argsort(x)[-n:]])

Original array:
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98]
[98]


# 15.How to create a record array from a regular array?

In [91]:
a1=np.array(['Veggie','Tomatoes','Chilli ','Carrot','Lemon'])
a2=np.array(['color','Red','Green','Orange','Yellow'])
result= np.core.records.fromarrays([a1, a2])
print(result[0])
print(result[1])
print(result[2])
print(result[3])
print(result[4])

('Veggie', 'color')
('Tomatoes', 'Red')
('Chilli ', 'Green')
('Carrot', 'Orange')
('Lemon', 'Yellow')
