QUES 1. CREATE A 3X3X3 ARRAY WITH RANDOM VALUES.

In [7]:
np.random.random

import numpy as np

M = np.random.random((3,3,3))
print(M)




[[[0.68084878 0.55940226 0.73635614]
  [0.38847048 0.96368727 0.37895563]
  [0.74947489 0.60133428 0.19352947]]

 [[0.60357523 0.05526024 0.37952887]
  [0.54159276 0.01045666 0.33995478]
  [0.22596259 0.81025767 0.37824531]]

 [[0.42879625 0.21892342 0.12243171]
  [0.69337385 0.6043443  0.47748515]
  [0.33990511 0.08683318 0.85928327]]]


QUES 2. CREATE A 5x5 MATRIX WITH VALUES 1,2,3,4 JUST BELOW THE DIAGONAL.

In [13]:
import numpy as np

a = np.diag(1+np.arange(4),k=-1)

print(Z)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


QUES 3. CREATE A 8x8 MATRIX AND FILL IT WITH A CHECKBOARD PATTERN.

In [21]:
m = np.zeros((8,8),dtype=int)
m[1::2,::2] = 1
m[::2,1::2] = 1
print(m)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


QUES 4. NORMALIZE A 5X5 RANDOM MATRIX

In [31]:
N = np.random.random((5,5))
N = (N - np.mean (N)) / (np.std (N))
print(N)

[[-0.11914995 -1.11716787  0.93448965 -1.74652143 -1.78359376]
 [ 0.12025738  0.6578671  -1.49632576 -0.20038021  1.96035531]
 [ 0.35399795  0.57455176  1.13698156  0.64525659  1.10491865]
 [-0.12371274 -0.80090862 -0.49969151 -1.74398065  0.00987333]
 [-0.13178036  1.03220455 -0.45856264  0.78510075  0.90592094]]


QUES 5. HOW TO FIND COMMON VALUES BETWEEN TWO ARRAYS?

In [37]:
import numpy as np
m1 = np.random.randint(0,10,20)
m2 = np.random.randint(0,10,30)
print(np.intersect1d(m1,m2))

[0 1 2 3 4 6 7 8 9]


 QUES 6. HOW TO KNOE THE DATES OF YESTERDAY, TODAY AND TOMORROW.

In [43]:
import numpy as np

yesterday = np.datetime64('today') - np.timedelta64(1)
today     = np.datetime64('today')
tomorrow  = np.datetime64('today') + np.timedelta64(1)
print(yesterday)
print(today)
print(tomorrow)

2020-08-04
2020-08-05
2020-08-06


QUES 7. CONSIDER TWO RANDOM ARAYS A AND B, CHECK IF THEY ARE EQUAL.

In [6]:
import numpy as np
A = np.random.randint(0,1,2)
B = np.random.randint(0,1,2)

equal = np.allclose(A,B)
print(equal)

equal = np.array_equal(A,B)
print(equal)


A = np.random.randint(0,3,6)
B = np.random.randint(0,3,6)

equal = np.allclose(A,B)
print(equal)

equal = np.array_equal(A,B)
print(equal)

True
True
False
False


QUES 8. CREATE RANDOM VECTOR OF SIZE 10 AND REPLACE THE MAXIMUM VALUE BY 0.

In [17]:
Z = np.random.random(10)
Z[Z.argmax()] = 0
print(Z)

[0.55498384 0.89696319 0.02940024 0.85758753 0.77587514 0.40312843
 0.         0.01499675 0.91440077 0.33365975]


QUES 9. HOW TO PRINT ALL THE VALUES OF AN ARRAY?

In [50]:
np.set_printoptions(threshold=float("inf"))
Z = np.zeros((16,16))
print(Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


QUES 10. SUBTRACT THE MEAN OF EACH ROW OF A MATRIX.

In [58]:
import numpy as np

X = np.random.rand(15, 20)

Y = X - X.mean(axis=1, keepdims=True)

print(Y)

[[-0.38068651 -0.07176847  0.11857157 -0.39123968 -0.36340481 -0.38336294
  -0.28259856  0.32139703  0.2458155   0.24457148  0.11846097 -0.07422151
  -0.34987057  0.11642547  0.34851892  0.22042823 -0.08156909  0.29315699
   0.09275845  0.25861754]
 [-0.20648389  0.10745813 -0.27863641  0.21703403 -0.32985473 -0.50857131
   0.38880659  0.38421247  0.42883566  0.00477421 -0.50754274 -0.28707723
   0.17523317  0.13065921  0.18662318  0.36920807 -0.1190908   0.21181052
  -0.4566263   0.08922817]
 [ 0.52643961 -0.05461244  0.30977741  0.05250576 -0.30703655 -0.40846207
  -0.1297441  -0.15764766 -0.41297441  0.03720078  0.01067051  0.04524726
   0.36456616 -0.33453121  0.50298058 -0.37444696  0.36268394 -0.18876537
  -0.17324797  0.32939672]
 [-0.29120625  0.20078598 -0.05166868  0.31672148  0.50098827 -0.39375072
   0.1074346   0.2859349   0.15791472  0.13261923 -0.13116436  0.28899735
  -0.24971578  0.101415   -0.24733912  0.30514768 -0.3087216  -0.38962333
  -0.09831836 -0.23645102]
 [-0

QUES 11. CONSIDER A GIVEN VECTOR, HOW TO ADD 1 TO EACH ELEMENT INDEXED BY A SECOND VECTOR (BE CAREFUL WITH REPEATED INDICES)?

In [70]:
import numpy as np

Z = np.ones(20)
I = np.random.randint(0, len(Z),30)
Z += np.bincount(I, minlength = len(Z))

print (Z)

[2. 1. 3. 2. 3. 1. 2. 5. 3. 2. 2. 5. 1. 4. 2. 4. 3. 1. 3. 1.]


In [71]:
np.add.at(Z, I, 1)

print(Z)


[3. 1. 5. 3. 5. 1. 3. 9. 5. 3. 3. 9. 1. 7. 3. 7. 5. 1. 5. 1.]


QUES 12. HOW TO GET THE DIAGONAL OF A DOT PRODUCT?

In [80]:
import numpy as np

A = np.random.uniform(0, 2, (10, 10))
B = np.random.uniform(0, 2, (10, 10))
print(A)
print(B)

prod1 = np.diag(np.dot(A,B))

[[1.86440169 0.23749545 1.08684047 0.93282813 1.65764823 0.6921135
  0.15470404 1.55886365 1.53253428 0.57227177]
 [0.65206529 1.84710266 1.21964892 0.34721108 1.24182216 0.15397963
  1.53443632 0.55919024 0.78611755 0.26384948]
 [0.8582459  1.97220271 1.84030917 0.98782792 0.59720706 0.9573046
  0.80725869 0.30228687 0.67470232 0.74579803]
 [1.64585891 1.82916324 0.68529215 0.74578758 1.3207229  1.61219989
  0.79944205 0.35774676 1.42638166 0.46379405]
 [0.26940191 0.21397841 1.71556591 1.97334029 1.3947712  0.91136047
  1.25695374 0.75556272 1.78173609 1.3019824 ]
 [0.14451086 0.02272041 0.30808733 0.76745482 1.10653276 0.06458717
  1.2093415  0.19759617 0.62598491 1.27598097]
 [1.03800733 0.16746095 0.25681547 0.97320297 0.76935157 0.14513327
  0.2566845  0.81885713 1.24030415 0.15500295]
 [0.16701366 0.10920045 1.85145579 0.38922971 1.35431301 0.37688388
  0.8589655  0.35380378 1.56199002 0.25665512]
 [0.54158602 0.76690816 0.52157759 0.91589986 0.39605708 0.24889761
  0.88244777 1

In [81]:
import numpy as np

A = np.random.uniform(0, 2, (10, 10))
B = np.random.uniform(0, 2, (10, 10))
print(A)
print(B)

prod = np.sum(A* B.T, axis = 1)

[[1.30643781 1.93518682 0.15670943 1.5773473  1.5875569  1.44422491
  0.86122984 1.0142655  0.35949761 1.77555017]
 [1.05488655 0.73551066 1.70824556 0.99629556 0.8717853  0.44641221
  0.72788383 1.06181168 1.7356835  1.65864182]
 [0.28975244 0.1837737  1.17526102 1.51070525 1.85579078 1.14276339
  0.75071925 0.63972524 0.68423512 0.32429497]
 [0.36226808 1.70728998 1.32384908 0.39420213 1.7485472  0.33025469
  0.94884103 1.84070068 1.38388753 0.08094921]
 [1.76454418 1.1882305  0.8396308  0.5159947  1.19595632 1.20607036
  1.08012101 0.51613215 0.61630164 1.40901779]
 [1.9352769  1.2209335  1.5036763  0.77592674 1.14394629 0.50039692
  1.98069192 1.00254397 0.20967367 0.83364646]
 [0.2196219  1.80649013 1.20534042 1.48808068 0.46241383 1.94030375
  0.35989256 0.22974984 0.28268917 1.9383107 ]
 [1.75388511 0.97076698 1.22734988 1.89107823 1.12149414 0.94603077
  1.36395925 0.04032943 1.37057023 0.81269944]
 [1.48728388 0.73138419 1.18310935 0.78398972 0.31573161 0.1537462
  0.71994773 

QUES 13. HOW TO FIND THE MOST FREQUENT VALUE IN AN ARRAY?

In [91]:
import numpy as np

s = np.random.randint(0, 20, 40)
print(s)
print(np.bincount(s).argmax())

[ 7  0  0 14  8  3  6  9  3  2 10  5 13 16 19 14 14  4 12 10  7  9  2 14
  9 16  2 12  2 14  9 19 11  6  8 15  1 18  8 11]
14


QUES 14. HOW TO GET THE n LARGEST VALUE OF AN ARRAY?

In [96]:
import numpy as np

M = np.arange(1500)
np.random.shuffle(M)
n = 10

print(M[np.argsort(M)[-n:]])

[1490 1491 1492 1493 1494 1495 1496 1497 1498 1499]


QUES 15. HOW TO CREATE A RECORD ARRAY FROM A REGULAR ARRAY?

In [111]:
M = np.array([("WORKING", 25.52, 8),
              ("INDIVIDUAL", 38.56, 12)])
O = np.core.records.fromarrays(M.T,
                               names='col1, col2, col3',
                               formats = 'S10, f8, i8')
print(O)

[(b'WORKING', 25.52,  8) (b'INDIVIDUAL', 38.56, 12)]
